finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
	
urlpatterns = [
	path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('finches/<int:finch_id>/add_birdseed/', views.add_birdseed, name='add_birdseed'),
    path('toys/', views.toys_index, name='toyindex'),
    path('toys/<int:toy_id>/', views.toys_detail, name='toydetail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    path('toys/<int:finch_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

SEEDS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Toy(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    price = models.IntegerField()

    def __str__(self):
        return f'{self.name} ({self.id})'
    
  
    def get_absolute_url(self):
        return reverse('detail', kwargs={'toy_id': self.id})

class Finch(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return f'{self.name} ({self.id})'
    
  
    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})

class Birdseed(models.Model):
    date = models.DateField('feeding date')
    seed = models.CharField(
        max_length=1,
        choices=SEEDS,
        default=SEEDS[0][0]
    )

    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_seed_display()} on {self.date}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Birdseed

class BirdseedForm(ModelForm):
  class Meta:
    model = Birdseed
    fields = ['date', 'seed']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Finch, Toy
from .forms import BirdseedForm

def home(request):
  return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
  finches = Finch.objects.all()
  return render(request, 'finches/index.html', 
  { 
    'finches': finches
    }
)

def toys_index(request):
  toys = Toy.objects.all()
  return render(request, 'toys/index.html', 
  { 
    'toys': toys
    }
)

def finches_detail(request, finch_id):
  finch = Finch.objects.get(id=finch_id)
  id_list = finch.toys.all().values_list('id')
  toys_finch_doesnt_have = Toy.objects.exclude(id__in=id_list)
  birdseed_form = BirdseedForm()
  return render(request, 'finches/detail.html', {
     'finch': finch, 'birdseed_form': birdseed_form,
     'toys': toys_finch_doesnt_have 
     })

def toys_detail(request, toy_id):
  toy = Toy.objects.get(id=toy_id)
  return render(request, 'toys/detail.html', {'toy': toy})

class FinchCreate(CreateView):
  model = Finch
  fields = ['name', 'breed', 'description', 'age']
  success_url = '/finches/{finch_id}'

class ToyCreate(CreateView):
  model = Toy
  fields = '__all__'
  success_url = '/toys/{toy_id}'

class FinchUpdate(UpdateView):
  model = Finch
  fields = ['breed', 'description', 'age']

class FinchDelete(DeleteView):
  model = Finch
  success_url = '/finches'

class ToyUpdate(UpdateView):
  model = Toy
  fields = ['color', 'price']

class ToyDelete(DeleteView):
  model = Toy
  success_url = '/toys'

def add_birdseed(request, finch_id):
  form = BirdseedForm(request.POST)
  if form.is_valid():
    new_birdseed = form.save(commit=False)
    new_birdseed.finch_id = finch_id
    new_birdseed.save()
  return redirect('detail', finch_id=finch_id)

def assoc_toy(request, finch_id, toy_id):
  Finch.objects.get(id=finch_id).toys.add(toy_id)
  return redirect('detail', finch_id=finch_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector</h1>
<hr>
<p>Hire the Finch Collector!</p>
<footer>All Rights Reserved, &copy; 2022 Finch Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View All My Finches</a></li>
          <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
          <li><a href="{% url 'toyindex' %}">View All My Toys</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finches Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.breed }}</p>
        <p>Description: {{ finch.description|linebreaks }}</p>
        {% if finch.age > 0 %}
          <p>Age: {{ finch.age }}</p>
        {% else %}
          <p>Age: Young Finch</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Edit</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action = "{% url 'add_birdseed' finch.id %}" method="POST">
    {% csrf_token %}
    {{ birdseed_form.as_p }}
    <input type="submit" class="btn" value="Add Birdseed">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Birdseed</th></tr>
      </thead>
      <tbody>
        {% for birdseed in finch.birdseed_set.all %}
          <tr>
            <td>{{birdseed.date}}</td>
            <td>{{birdseed.get_seed_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Toys</h3>
    {% if finch.toys.count %}
      {% for toy in cat.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys 😿</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' finch.id toy.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{toy.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_seed');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
  <div class="card">
    <a href ="{% url 'detail' finch.id %}">
        <div class="card-content">
        <span class="card-title">{{ finch.name }}</span>
        <p>Breed: {{ finch.breed }}</p>
        <p>Description: {{ finch.description }}</p>
        {% if finch.age > 0 %}
            <p>Age: {{ finch.age }}</p>
        {% else %}
            <p>Age: Young Finch</p>
        {% endif %}
        </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}

    <h1>Home</h1>

    {% endblock %}

</body>
</html>

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Finch</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/toy_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toydetail' toy.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/toy_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Toy</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/toys/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Toys Details</h1>

<div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
        <p>Price: {{ toy.price }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
</div>

{% endblock %}

main_app/templates/toys/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Toys List</h1>

{% for toy in toys %}
  <div class="card">
    <a href ="{% url 'toydetail' toy.id %}">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
            <p>Price: {{ toy.price }}</p>
        </div>
    </a>
  </div>
{% endfor %}

{% endblock %}